language: python
python:
  - "2.7"

install:
  - pip install tinkerer
  - pip install sphinxjp.themes.tinkerturquoise

env:
  global:
  - ENCRYPTION_LABEL: "8c1ec1f6b778"
  - COMMIT_AUTHOR_EMAIL: "ferrishu3886@gmail.com"

script:
  - pwd

after_success:
  - bash ./deploy.sh

notifications:
  email:
    recipients:
      - ferrishu3886@gmail.com
    on_success: change # option [alway|never|change]
    on_failure: always